[reddit_oauth]

reddit_client_id = "kblNpw3CIu3XidD6iYdtrw"
reddit_secret = "2Vqmx6bpXG8AGwb2OJahRzD8jfFA-Q"

[talesforretail]

flairs = ["medium", "long"]

[talesfromtechsupport]

flairs = ["medium", "short"]